Repository leonbjorklund/QuizIt, pull requests merged in 2024-01, with the labels that each got.

#55 54 refactor homescene
  src/assets/strings/home.json
  src/chakra/theme.ts
  src/components/HomeScene/HomeScene.tsx
  src/components/HomeScene/components/Form.tsx
  src/components/HomeScene/components/index.ts
  src/components/HomeScene/index.ts
Labels: user story, Sprint 3

#57 29 ai creation creating prompts
  src/App.tsx
  src/assets/index.ts
  src/assets/prompt/getPrompt.ts
  src/assets/prompt/index.ts
  src/components/HomeScene/HomeScene.tsx
  src/components/LoadingScene/LoadingScene.tsx
  src/components/OptionsScene/OptionsScene.tsx
Labels: user story, Sprint 3

#62 39 decide ai token handling
  .eslintrc
  server/queryGPT.js
  src/context/AppContext.tsx
  src/context/generatePrompt.ts
  src/context/sendToGPT.ts
  src/utils/types.ts
Labels: user story, Sprint 4

#63 33 deploy to netlify
  .eslintrc
  .gitignore
  netlify.toml
  netlify/functions/api.js
  netlify/functions/lib/queryGPT.js
  package-lock.json
  package.json
  server/app.js
  server/queryGPT.js
  vite.config.ts
Labels: user story, Sprint 4

#65 35 codebase review
  .gitignore
  README.md
  favicon.png
  filenest.txt
  netlify/functions/api.js
  netlify/functions/lib/queryGPT.js
  server/app.js
  server/asd.json
  server/queryGPT.js
  src/App.tsx
  src/AppContext.tsx
  src/scenes/EndScene/EndScene.tsx
  src/scenes/EndScene/styles.ts
  src/scenes/HomeScene/HomeScene.tsx
  src/scenes/HomeScene/QuizInputForm.tsx
  src/scenes/LoadingScene/LoadingAnimation.tsx
  src/scenes/LoadingScene/LoadingScene.tsx
  src/scenes/LoadingScene/index.ts
  src/scenes/OptionsScene/Option.tsx
  src/scenes/OptionsScene/OptionsScene.tsx
  src/scenes/PlayScene/PlayScene.tsx
  src/scenes/PlayScene/testQuizData.json
  src/shared-components/Header/DarkLightModeButton.tsx
  src/shared-components/Header/Header.tsx
  src/shared-components/Header/HeaderLogoButton.tsx
  src/shared-components/Header/styles.ts
  src/shared-components/Radio/Radio.tsx
  src/shared-components/Radio/RadioStyles.tsx
  src/shared-components/Radio/getRadioBackgroundColor.tsx
  src/shared-components/Wrappers/SceneCard.tsx
  src/shared-components/Wrappers/SceneContainer.tsx
  src/theme.ts
  src/utils/fetchQuizData.ts
  src/utils/generatePrompt.ts
  src/utils/types.ts
  src/utils/updateQuiz.ts
Labels: user story, Sprint 6

#67 sizes adjusted
  server/app.js
  server/queryGPT.js
  src/AppContext.tsx
  src/scenes/EndScene/styles.ts
  src/scenes/HomeScene/styles.ts
  src/scenes/PlayScene/PlayScene.tsx
  src/scenes/PlayScene/styles.ts
  src/shared-components/Header/styles.ts
  src/shared-components/Radio/RadioStyles.tsx
  src/shared-components/Wrappers/SceneCard.tsx
  src/shared-components/Wrappers/SceneContainer.tsx
  src/theme.ts
  src/utils/GlobalStyles.tsx
  vite.config.ts
Labels: user story, Sprint 6
